on:
  push

jobs:
  build_pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}
            fetch-depth: 0

      - name: Build Pack from TS
        run: |
          npm i sandstone sandstone-cli
          npm run build
          mv .pack/mountedwasd/* .

      - name: Add & Commit changes
        run: |
          git checkout generated
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -A ./data
          git add pack.mcmeta
          git diff-index --quiet HEAD || git commit -m 'Updated Pack files'

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
