on:
  push

jobs:
  build_pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}
            fetch-depth: 0

      - name: Build Pack from TS
        run: |
          npm i sandstone sandstone-cli
          npm run build
          git clone https://github.com/MulverineX/mountedwasd gen
          cd gen
          git checkout generated
          rm -rf data/* pack.mcmeta
          mv ../.pack/mountedwasd/* data

      - name: Add & Commit changes
        run: |
          cd gen
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Updated Pack files'

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
